services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - nats

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - nats

  agent:
    build:
      context: .
      dockerfile: ./apps/agent/Dockerfile
      target: development
    command: npm run start:dev agent
    env_file:
      - ./apps/agent/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    depends_on:
      - nats

  channel:
    build:
      context: .
      dockerfile: ./apps/channel/Dockerfile
      target: development
    command: npm run start:dev channel
    env_file:
      - ./apps/channel/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
    depends_on:
      - nats

  mongo:
    image: mongo

  nats:
    image: nats
    ports:
      - '4222:4222'
      - '8222:8222'
