services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  container:
    build:
      context: .
      dockerfile: ./apps/container/Dockerfile
      target: development
    command: npm run start:dev container
    env_file:
      - ./apps/container/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
